// go generate
// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT THIS FILE
// ~~ This file is not generated by hand ~~
// ~~ generated on: 2017-11-08 12:26:48.758541788 +0000 UTC ~~

package logger

import (
	"net/http"
)

// String is the string representation of the color
func (lc LogColor) String() string {
	switch lc {
	case Black:
		return "Black"
	case Blue:
		return "Blue"
	case Cyan:
		return "Cyan"
	case Green:
		return "Green"
	case Magenta:
		return "Magenta"
	case Red:
		return "Red"
	case White:
		return "White"
	case Yellow:
		return "Yellow"
	}

	return "unknown"
}

// ToESCColor is the escape string representation of the color int32 number
func (lc LogColor) ToESCColor() string {
	switch lc {
	case Black:
		return "\x1b[30m"
	case Blue:
		return "\x1b[34m"
	case Cyan:
		return "\x1b[36m"
	case Green:
		return "\x1b[32m"
	case Magenta:
		return "\x1b[35m"
	case Red:
		return "\x1b[31m"
	case White:
		return "\x1b[37m"
	case Yellow:
		return "\x1b[33m"
	}

	return "0"
}

// Level returns the log level used
func Level() (lvl level) {
	lvl.Debug = 8
	lvl.Error = 4
	lvl.Fatal = 32
	lvl.Info = 1
	lvl.Panic = 64
	lvl.Trace = 16
	lvl.Warn = 2
	return lvl
}

// String is the string representation of the log level
func (ll LogLevel) String() string {
	switch ll {
	case 8:
		return "Debug"
	case 4:
		return "Error"
	case 32:
		return "Fatal"
	case 1:
		return "Info"
	case 64:
		return "Panic"
	case 16:
		return "Trace"
	case 2:
		return "Warn"
	}

	return "unknown"
}

// StringWithColon is the string representation of the log level with trailing colon
func (ll LogLevel) StringWithColon() string {
	switch ll {
	case 8:
		return "Debug:"
	case 4:
		return "Error:"
	case 32:
		return "Fatal:"
	case 1:
		return "Info:"
	case 64:
		return "Panic:"
	case 16:
		return "Trace:"
	case 2:
		return "Warn:"
	}

	return "unknown"
}

// Short is the short three letter abbreviation of the log level
func (ll LogLevel) Short() string {
	switch ll {
	case 8:
		return "DBG"
	case 4:
		return "ERR"
	case 32:
		return "FAT"
	case 1:
		return "INF"
	case 64:
		return "PAN"
	case 16:
		return "TRC"
	case 2:
		return "WRN"
	}

	return "unknown"
}

// Logger is the main interface that is presented as a logger
type Logger interface {
	Color(LogColor) Logger
	NoColor() Logger
	Field(string, interface{}) Logger
	Fields(...keyValue) Logger
	HTTPMiddleware(next http.Handler) http.Handler
	OnErr(error) Logger
	Suppress()
	UnSuppress()

	Debug(...interface{})
	Debugf(string, ...interface{})
	Error(...interface{})
	Errorf(string, ...interface{})
	Fatal(...interface{})
	Fatalf(string, ...interface{})
	Fatalln(...interface{})
	Info(...interface{})
	Infof(string, ...interface{})
	Panic(...interface{})
	Panicf(string, ...interface{})
	Panicln(...interface{})
	Print(...interface{})
	Printf(string, ...interface{})
	Println(...interface{})
	Trace(...interface{})
	Tracef(string, ...interface{})
	Warn(...interface{})
	Warnf(string, ...interface{})
}

// Debug is the generated logger function to satisfy the interface
func (l *DefaultLogger) Debug(iface ...interface{}) {
	l.println(8, Cyan.ToESCColor(), iface...)
}

// Debugf is the generated logger function to satisfy the interface
func (l *DefaultLogger) Debugf(fmt string, iface ...interface{}) {
	l.printf(8, Cyan.ToESCColor(), fmt, iface...)
}

// Error is the generated logger function to satisfy the interface
func (l *DefaultLogger) Error(iface ...interface{}) {
	l.println(4, Red.ToESCColor(), iface...)
}

// Errorf is the generated logger function to satisfy the interface
func (l *DefaultLogger) Errorf(fmt string, iface ...interface{}) {
	l.printf(4, Red.ToESCColor(), fmt, iface...)
}

// Fatal is the generated logger function to satisfy the interface
func (l *DefaultLogger) Fatal(iface ...interface{}) {
	l.print(32, Red.ToESCColor(), iface...)
}

// Fatalf is the generated logger function to satisfy the interface
func (l *DefaultLogger) Fatalf(fmt string, iface ...interface{}) {
	l.printf(32, Red.ToESCColor(), fmt, iface...)
}

// Fatalln is the generated logger function to satisfy the interface
func (l *DefaultLogger) Fatalln(iface ...interface{}) {
	l.println(32, Red.ToESCColor(), iface...)
}

// Info is the generated logger function to satisfy the interface
func (l *DefaultLogger) Info(iface ...interface{}) {
	l.println(1, Green.ToESCColor(), iface...)
}

// Infof is the generated logger function to satisfy the interface
func (l *DefaultLogger) Infof(fmt string, iface ...interface{}) {
	l.printf(1, Green.ToESCColor(), fmt, iface...)
}

// Panic is the generated logger function to satisfy the interface
func (l *DefaultLogger) Panic(iface ...interface{}) {
	l.print(64, Red.ToESCColor(), iface...)
}

// Panicf is the generated logger function to satisfy the interface
func (l *DefaultLogger) Panicf(fmt string, iface ...interface{}) {
	l.printf(64, Red.ToESCColor(), fmt, iface...)
}

// Panicln is the generated logger function to satisfy the interface
func (l *DefaultLogger) Panicln(iface ...interface{}) {
	l.println(64, Red.ToESCColor(), iface...)
}

// Print is the generated logger function to satisfy the interface
func (l *DefaultLogger) Print(iface ...interface{}) {
	l.print(1, Green.ToESCColor(), iface...)
}

// Printf is the generated logger function to satisfy the interface
func (l *DefaultLogger) Printf(fmt string, iface ...interface{}) {
	l.printf(1, Green.ToESCColor(), fmt, iface...)
}

// Println is the generated logger function to satisfy the interface
func (l *DefaultLogger) Println(iface ...interface{}) {
	l.println(1, Green.ToESCColor(), iface...)
}

// Trace is the generated logger function to satisfy the interface
func (l *DefaultLogger) Trace(iface ...interface{}) {
	l.println(16, Blue.ToESCColor(), iface...)
}

// Tracef is the generated logger function to satisfy the interface
func (l *DefaultLogger) Tracef(fmt string, iface ...interface{}) {
	l.printf(16, Blue.ToESCColor(), fmt, iface...)
}

// Warn is the generated logger function to satisfy the interface
func (l *DefaultLogger) Warn(iface ...interface{}) {
	l.println(2, Yellow.ToESCColor(), iface...)
}

// Warnf is the generated logger function to satisfy the interface
func (l *DefaultLogger) Warnf(fmt string, iface ...interface{}) {
	l.printf(2, Yellow.ToESCColor(), fmt, iface...)
}

// Color is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Color(x LogColor) Logger { return l }

// NoColor is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) NoColor() Logger { return l }

// Field is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Field(s string, iface interface{}) Logger {
	return l
}

// Fields is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Fields(kv ...keyValue) Logger {
	return l
}

// HTTPMiddleware is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) HTTPMiddleware(next http.Handler) (r http.Handler) {
	return next
}

// OnErr is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) OnErr(x error) Logger { return l }

// Suppress is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Suppress() {}

// UnSuppress is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) UnSuppress() {}

// Debug is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Debug(iface ...interface{}) { return }

// Debugf is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Debugf(fmt string, iface ...interface{}) { return }

// Debugln is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Debugln(iface ...interface{}) { return }

// Error is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Error(iface ...interface{}) { return }

// Errorf is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Errorf(fmt string, iface ...interface{}) { return }

// Errorln is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Errorln(iface ...interface{}) { return }

// Fatal is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Fatal(iface ...interface{}) { return }

// Fatalf is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Fatalf(fmt string, iface ...interface{}) { return }

// Fatalln is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Fatalln(iface ...interface{}) { return }

// Info is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Info(iface ...interface{}) { return }

// Infof is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Infof(fmt string, iface ...interface{}) { return }

// Infoln is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Infoln(iface ...interface{}) { return }

// Panic is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Panic(iface ...interface{}) { return }

// Panicf is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Panicf(fmt string, iface ...interface{}) { return }

// Panicln is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Panicln(iface ...interface{}) { return }

// Print is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Print(iface ...interface{}) { return }

// Printf is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Printf(fmt string, iface ...interface{}) { return }

// Println is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Println(iface ...interface{}) { return }

// Trace is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Trace(iface ...interface{}) { return }

// Tracef is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Tracef(fmt string, iface ...interface{}) { return }

// Traceln is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Traceln(iface ...interface{}) { return }

// Warn is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Warn(iface ...interface{}) { return }

// Warnf is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Warnf(fmt string, iface ...interface{}) { return }

// Warnln is the nilLogger function to satisfy the interface. It does nothing.
func (l *nilLogger) Warnln(iface ...interface{}) { return }

// Debug is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Debug(iface ...interface{}) {
	l.println(8, l.color, iface...)
}

// Debugf is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Debugf(fmt string, iface ...interface{}) {
	l.printf(8, l.color, fmt, iface...)
}

// Error is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Error(iface ...interface{}) {
	l.println(4, l.color, iface...)
}

// Errorf is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Errorf(fmt string, iface ...interface{}) {
	l.printf(4, l.color, fmt, iface...)
}

// Fatal is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Fatal(iface ...interface{}) {
	l.print(32, l.color, iface...)
}

// Fatalf is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Fatalf(fmt string, iface ...interface{}) {
	l.printf(32, l.color, fmt, iface...)
}

// Fatalln is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Fatalln(iface ...interface{}) {
	l.println(32, l.color, iface...)
}

// Info is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Info(iface ...interface{}) {
	l.println(1, l.color, iface...)
}

// Infof is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Infof(fmt string, iface ...interface{}) {
	l.printf(1, l.color, fmt, iface...)
}

// Panic is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Panic(iface ...interface{}) {
	l.print(64, l.color, iface...)
}

// Panicf is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Panicf(fmt string, iface ...interface{}) {
	l.printf(64, l.color, fmt, iface...)
}

// Panicln is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Panicln(iface ...interface{}) {
	l.println(64, l.color, iface...)
}

// Print is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Print(iface ...interface{}) {
	l.print(1, l.color, iface...)
}

// Printf is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Printf(fmt string, iface ...interface{}) {
	l.printf(1, l.color, fmt, iface...)
}

// Println is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Println(iface ...interface{}) {
	l.println(1, l.color, iface...)
}

// Trace is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Trace(iface ...interface{}) {
	l.println(16, l.color, iface...)
}

// Tracef is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Tracef(fmt string, iface ...interface{}) {
	l.printf(16, l.color, fmt, iface...)
}

// Warn is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Warn(iface ...interface{}) {
	l.println(2, l.color, iface...)
}

// Warnf is the generated colorLogger function to satisfy the interface
func (l *colorLogger) Warnf(fmt string, iface ...interface{}) {
	l.printf(2, l.color, fmt, iface...)
}
